version: "3.8"
services:
    calc-api:
        image: deanreynolds/lbg-grad-compose-api
        build: ./calculator-api
        ports:
            -   target: 8080
                published: 8081
    front-a:
        image: deanreynolds/lbg-grad-compose-front-a
        build: 
            context: ./frontend-1
            args:
                SERVER_URL: $(SERVER_URL)
        ports:
            -   target: 80
                published: 80
    front-b:
        image: deanreynolds/lbg-grad-compose-front-b
        build:
            context: ./frontend-2
            args:
                SERVER_URL: $(SERVER_URL)
        ports:
            -   target: 80
                published: 81
